# Variables globales
nfs_version: 3
domain: projet.local
net_management: "192.168.198.0/24"

# Cumulus / NCLU
# Description utilisee pour tracer les commits executes par Ansible
nclu_commit_description_prefix: "Ansible"
nclu_cleanup_commit_description: "full reset baseline before any playbook"
nclu_use_rollback_cleanup: true
nclu_cleanup_rollback_steps: 3

# VLANs
vlan_machine1: 10
vlan_machine2: 20

# Réseaux
net_vlan10: "192.168.10.0/24"
net_vlan20: "192.168.20.0/24"

# IPs
ip_machine1: "192.168.10.2"
ip_machine2: "192.168.20.4"
ip_serveur_vlan10: "192.168.10.10"
ip_serveur_vlan20: "192.168.20.10"

# IP NFS à utiliser par client selon la phase VLAN/bonding
nfs_server_ip_map:
  machine1: "192.168.10.10"
  machine2: "192.168.20.10"

# Points de montage NFS par client
nfs_client_mounts:
  machine1: "/machine1"
  machine2: "/machine2"

# Interface de labo utilisée pour la partie 1 (Single attachment)
lab_client_interface: "ens34"

# Bonding LACP Côté Client (ensX) - UNCHANGED
bond_name: "bond0"
bond_iface1: "ens34"
bond_iface2: "ens35"

# --- CABLAGE / TOPOLOGIE PHYSIQUE (Mis à jour selon le tableau) ---

# Switch 3 (Gateway / Distribution Layer)
sw3_uplink_port: "swp1"
sw3_vlan_transit_ports: "swp2-3" # Rows 2-3 (Connect to SW1, SW2)
# Miscellaneous/BGP
sw3_ip_toward_sw2: "192.168.2.1"
sw3_ip_toward_sw1: "192.168.1.1"
# Switch 1 (MLAG PEER 1/A)
sw1_uplink_port: "swp2"
sw1_vlan_transit_port: "swp2" # Row 2 (Connect to SW3)
sw1_nfs_ports: "swp3-4" # Rows 5-6 (Connect to NFS ens35/34)
sw1_peer_ports: "swp5-6" # Rows 7-8 (MLAG Peering links to SW2)
sw1_machine1_port: "swp7"
sw1_machine2_port: "swp8"
# Switch 2 (MLAG PEER 2/B)
sw2_uplink_port: "swp2"
sw2_vlan_transit_port: "swp2" # Row 3 (Connect to SW3)
sw2_peer_ports: "swp3-4" # Rows 12-13 (MLAG Peering links to SW1:swp5-6)
sw2_machine2_port: "swp5" # Row 14 (Connect to M2 ens34)
sw2_machine1_port: "swp6" # Row 15 (Connect to M1 ens35) - segment mlag2

# ------------------------------------------------------------------

# Passerelles VLAN (VIP VRR / switch3)
gw_vlan10: "192.168.10.1"
gw_vlan20: "192.168.20.1"

stp_client_ips:
  machine1: "192.168.10.2"
  machine2: "192.168.10.3"
