---
- name: Configuration VRR - Routeur 1 (Switch3)
  hosts: switch3
  become: yes
  tasks:
    - name: Restore the permanent backup for this switch
      command: "config-restore -f -b config_backup-2026-03-18-20.08.12_cumulus-perm"

    - name: net abort pour annuler les changements en attente
      command: net abort
      ignore_errors: yes

    - name: Activer IP forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present

    - name: Configuration VRR sur SVI via NCLU
      ansible.builtin.command: "{{ item }}"
      loop:
        # 1. Trunks L2
        - "net add bridge bridge vlan-aware"
        - "net add bridge bridge ports swp2,swp3"
        - "net add interface swp2 bridge trunk vlans 10,20"
        - "net add interface swp3 bridge trunk vlans 10,20"

        # 2. VLAN 10 : IP physique (.3) + IP Virtuelle VRR (.254)
        - "net add vlan 10 ip address 192.168.1.3/24"
        - "net add vlan 10 ip address-virtual 00:00:5E:00:01:01 192.168.1.254/24"

        # 3. VLAN 20 : IP physique (.3) + IP Virtuelle VRR (.254)
        - "net add vlan 20 ip address 192.168.2.3/24"
        - "net add vlan 20 ip address-virtual 00:00:5E:00:01:02 192.168.2.254/24"
        - "net commit"

- name: Configuration VRR - Routeur 2 (Switch3b)
  hosts: switch3b
  become: yes
  tasks:
    - name: Restore the backup for switch3b
      command: config-restore -f -b config_backup-2026-03-27-18.58.21_cumulus-perm

    - name: net abort pour annuler les changements en attente
      command: net abort
      ignore_errors: yes

    - name: Activer IP forwarding
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present

    - name: Configuration VRR sur SVI via NCLU
      ansible.builtin.command: "{{ item }}"
      loop:
        # 1. Trunks L2
        - "net add bridge bridge vlan-aware"
        - "net add bridge bridge ports swp2,swp3"
        - "net add interface swp2 bridge trunk vlans 10,20"
        - "net add interface swp3 bridge trunk vlans 10,20"

        # 2. VLAN 10 : IP physique (.4) + IP Virtuelle VRR (.254)
        - "net add vlan 10 ip address 192.168.1.4/24"
        - "net add vlan 10 ip address-virtual 00:00:5E:00:01:01 192.168.1.254/24"

        # 3. VLAN 20 : IP physique (.4) + IP Virtuelle VRR (.254)
        - "net add vlan 20 ip address 192.168.2.4/24"
        - "net add vlan 20 ip address-virtual 00:00:5E:00:01:02 192.168.2.254/24"
        - "net commit"
