---
- name: Installer le paquet ifenslave (nécessaire pour le bonding sous Debian)
  ansible.builtin.apt:
    name: ifenslave
    state: present

- name: S'assurer que le module kernel "bonding" est chargé
  ansible.builtin.modprobe:
    name: bonding
    state: present

- name: Déployer la configuration réseau (interfaces)
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces.d/bonding
    owner: root
    group: root
    mode: "0644"

- name: Appliquer la configuration réseau
  ansible.builtin.systemd:
    name: networking
    state: restarted
