---
- name: 🐧 Configuration du Bonding LACP sur les serveurs Debian
  hosts: clients
  become: yes

  tasks:
    - name: Mettre à jour le cache APT
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Installer le paquet ifenslave (nécessaire pour le bonding sous Debian)
      ansible.builtin.apt:
        name: ifenslave
        state: present

    - name: S'assurer que le module kernel "bonding" est chargé
      ansible.builtin.modprobe:
        name: bonding
        state: present

    - name: Déployer la configuration réseau (interfaces)
      ansible.builtin.template:
        src: interfaces.j2
        dest: /etc/network/interfaces.d/bonding
        owner: root
        group: root
        mode: "0644"
      notify: Redémarrer le service réseau

  handlers:
    - name: Redémarrer le service réseau
      ansible.builtin.service:
        name: networking
        state: restarted
