# ==============================================
# Inventaire du projet M1 ADMINSYSRES2
# ==============================================

[switches]
switch1 ansible_host=192.168.198.11
switch2 ansible_host=192.168.198.12
switch3 ansible_host=192.168.198.13

[switches:vars]
ansible_user=cumulus
ansible_password=ansible123
ansible_become_pass=ansible123
ansible_python_interpreter=/usr/bin/python3

[switch_l2]
switch1
switch2

[switch_l3]
switch3

[servers]
serveur-nfs ansible_host=192.168.198.20

[servers:vars]
ansible_user=ansible
ansible_password=ansible123
ansible_python_interpreter=/usr/bin/python3

[clients]
machine1 ansible_host=192.168.198.31    
machine2 ansible_host=192.168.198.32

[clients:vars]
ansible_user=ansible
ansible_password=ansible
ansible_python_interpreter=/usr/bin/python3

[T3:children]
switch_l2
switch_l3
clients


[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'