bridge_ports: "swp2,swp5,swp7"
stp_ports:
  - swp7
  - swp2
  - swp5

stp_blocked_port: swp3
# host_vars/switch1.yml
ansible_host: 192.168.198.11

peerlink_slaves: swp5-6
peer_mgmt_ip: 192.168.19<8.12 # switch2 mgmt IP
clag_priority: 4096 # lower = primary
machine1_port: swp4
machine2_port: swp7
uplink_port: swp1
