bridge_ports: "swp2,swp5,swp7"
stp_ports:
  - swp7
  - swp2
  - swp5

stp_blocked_port: swp3
# host_vars/switch1.yml
ansible_host: 192.168.198.11

peerlink_slaves: swp5-6
peer_mgmt_ip: 192.168.198.12 # switch2 mgmt IP
clag_priority: 4096 # lower = primary

# Per-switch logical ports are defined centrally in group_vars/all.yml
# Keep only host-specific settings here to avoid redundancy.
sw1_uplink_port: "swp2"
sw1_vlan_transit_port: "swp2"
sw1_nfs_ports: "swp3-4"
sw1_peer_ports: "swp5-6"
sw1_machine1_port: "swp7"
sw1_machine2_port: "swp8"

maxport: 8
sw1_uplink_portRedundance: "swp9"
